name: restaurant_app
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0+5

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  flutter_rating_bar: ^4.0.1
  http: ^0.13.5
  provider: ^6.0.4
  lottie: ^2.0.0
  shared_preferences: ^2.0.15
  sqflite: ^2.2.0+3
  intl: ^0.18.0
  flutter_local_notifications: ^13.0.0
  rxdart: ^0.27.7
  android_alarm_manager_plus: ^2.1.0
  device_info_plus: ^8.1.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo/logo.png'
  adaptive_icon_background: 'assets/logo/background.png'
  adaptive_icon_foreground: 'assets/logo/foreground.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/food.png
    - assets/images/drink.png
    - assets/images/search-restaurant.png
    - assets/images/not-found.png
    - assets/images/empty-data.png
    - assets/images/no-internet.png
    - assets/lotties/loading.json
    - assets/logo/logo.png